[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/news/*"
  to = "/.netlify/functions/news/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200